FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libsqlite3-dev \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install dbt-core dbt-duckdb

WORKDIR /opt/airflow/dbt_project

ENTRYPOINT ["bash"]