default:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /opt/airflow/duckdb_data/airpolandweather.db
      extensions:
        - parquet
        - httpfs
      settings:
        s3_region: 'eu-central-1'
        s3_endpoint: 'http://minio:9000'
        s3_access_key_id: "{{ env_var('MINIO_ACCESS_KEY') }}"
        s3_secret_access_key: "{{ env_var('MINIO_SECRET_KEY') }}"